services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MensCircle\Sitepackage\:
    resource: '../Classes/*'

  voku\helper\HtmlMin:
    class: voku\helper\HtmlMin
    public: true
