name: mens-circle/feature
typeName: menscircle_feature
group: common
prefixFields: true
prefixType: full
fields:
  - identifier: TYPO3/Header
    type: Basic
  - identifier: bodytext
    type: Text
    useExistingField: true