name: Deploy Files

on:
  push:
    branches:
      - feature/typo3
  # Enables manually triggering of Workflow with file synchronization option
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "delta"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          args: --no-progress --no-interaction --optimize-autoloader --no-progress --ignore-platform-reqs

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

      - name: "Deploy"
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'hosting203243'
          server: 'mens-circle.de'
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
          local_path: './*'
          remote_path: '/mens-circle.de/httpdocs'
          sftpArgs: '-o ConnectTimeout=5'