name: Deploy Files

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: "${{ runner.os }}-${{ hashFiles('**/composer.lock') }}"
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          args: --no-progress --no-interaction --optimize-autoloader --no-progress --ignore-platform-reqs

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "./"
          REMOTE_HOST: mens-circle.de
          REMOTE_USER: viking
          TARGET: /home/viking/html/mens-circle.de
          EXCLUDE: ".env, .github, .git, .ddev, node_modules, fileadmin, config/system/additional.php"

      - name: Post deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: mens-circle.de
          username: viking
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/viking/html/mens-circle.de
            vendor/bin/typo3 install:fixfolderstructure
            vendor/bin/typo3 database:updateschema
            vendor/bin/typo3 cache:flush
            vendor/bin/typo3 language:update
