name: mens-circle/about
typeName: menscircle_about
group: common
prefixFields: true
prefixType: full
fields:
  - identifier: header
    useExistingField: true
  - identifier: subheader
    useExistingField: true
  - identifier: bodytext
    type: Textarea
    useExistingField: true
    enableRichtext: true
  - identifier: image
    useExistingField: true
    type: File
    minitems: 1
    maxitems: 1
    allowed: common-image-types