inheritDefault: true
mutations:
  - mode: set
    directive: 'default-src'
    sources:
      - "'self'"

  - mode: extend
    directive: 'img-src'
    sources:
      - 'data:'
      - 'https://*.basemaps.cartocdn.com'

  - mode: extend
    directive: 'font-src'
    sources:
      - 'data:'

  - mode: extend
    directive: 'script-src'
    sources:
      - "'unsafe-inline'"
      - 'https://tracking.letsbenow.de/'
      - 'https://static.cloudflareinsights.com/'

  - mode: extend
    directive: 'connect-src'
    sources:
      - "'unsafe-inline'"
      - 'https://tracking.letsbenow.de/'

  - mode: set
    directive: 'style-src'
    sources:
      - "'self'"
      - "'unsafe-inline'"
